# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# RUNTIME MODES:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              this_script.py
#              cadnx/
#   3. Run manually from the NX UI. MCP tools review APIs but do not execute.
#   4. The user prepares NX; the agent must not launch/close NX or overwrite
#      prior artifacts.
# ----------------------------------------------------------------------------

import json
import os
import sys

# Ensure cadnx is importable on the NX machine.
# Adjust these paths if cadnx/ is in a different location.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


EXECUTION_POLICY = {
    "mode": "mcp_review",
    "manual_user_run_required": True,
    "agent_execution": False,
    "requires_prepared_nx_environment": True,
    "allow_launch_or_close_nx": False,
    "allow_existing_work_part": False,
    "allow_overwrite": False,
    "managed_mode": False,
    "max_repair_attempts": 3,
}
DESIGN_LEDGER = {
    "task": "replace with generated task name",
    "capability_level": "stable_wrapper",
    "target_nx_version": "unknown",
    "expected_body_count": 1,
    "critical_features": [],
    "optional_features": [],
    "outputs": ["native_prt", "step"],
}


def allocate_run_context():
    journal_base = os.path.splitext(os.path.abspath(__file__))[0]
    sequence = 1
    while True:
        run_id = "run_%03d" % sequence
        run_base = journal_base + "_" + run_id
        candidates = [run_base + suffix for suffix in (".prt", ".step", ".nxreport.json", ".log")]
        if not any(os.path.exists(path) for path in candidates):
            return run_id, run_base
        sequence += 1


def write_runtime_report(report, path):
    with open(path, "w", encoding="utf-8") as stream:
        json.dump(report, stream, indent=2, sort_keys=True)
    print("NXCAD_RUNTIME_REPORT:", path)


def build(run_base: str, output_path: str = None):
    b = NXBuilder(part_path=run_base, force_new_part=not EXECUTION_POLICY["allow_existing_work_part"])

    # Parameters
    # Agent defines all named dimensions here, e.g.:
    # length = 100
    # width = 60
    # height = 20

    # Modeling
    # Use NXBuilder calls when they directly match the intended geometry.
    # Use raw NXOpen builders directly when they produce higher-fidelity NX
    # geometry; confirm raw API shapes through MCP API-review mode when
    # available.
    # Agent inserts NXBuilder calls here, e.g.:
    # body = b.box(length, width, height, origin=(0, 0, 0))
    # hole1 = b.hole(8, height + 2, position=(20, 15, height))
    # b.boolean_subtract(body, hole1)
    # b.chamfer(b.get_top_edges(body), offset=2)
    # Return only after each DESIGN_LEDGER critical feature is committed; main()
    # must set the corresponding report critical_features entry to True.

    # Export
    if output_path is None:
        output_path = run_base + ".step"
    output_path = b.export_step(output_path)
    return b, output_path


def main():
    output = sys.argv[1] if len(sys.argv) > 1 else None
    run_id, run_base = allocate_run_context()
    report_path = run_base + ".nxreport.json"
    report = {
        "schema_version": 2,
        "nx_version": DESIGN_LEDGER["target_nx_version"],
        "probe": os.path.splitext(os.path.basename(__file__))[0],
        "run_id": run_id,
        "result": "running",
        "execution": {
            "actor": "user",
            "transport": "nx_ui",
            "tool": "nx_ui",
        },
        "journal": {"path": os.path.abspath(__file__), "working_dir": _SCRIPT_DIR},
        "model": {
            "body_count": None,
            "expected_body_count": DESIGN_LEDGER["expected_body_count"],
            "critical_features": {name: False for name in DESIGN_LEDGER["critical_features"]},
        },
        "artifacts": {},
        "warnings": [],
    }
    try:
        builder, step_path = build(run_base, output)
        for name in DESIGN_LEDGER["critical_features"]:
            report["model"]["critical_features"][name] = True
        body_count = len(list(builder.part.Bodies))
        report["model"]["body_count"] = body_count
        if body_count != DESIGN_LEDGER["expected_body_count"]:
            raise RuntimeError(
                "Expected %d final body/bodies, found %d"
                % (DESIGN_LEDGER["expected_body_count"], body_count)
            )
        native_path = getattr(builder.part, "FullPath", "")
        report["artifacts"]["prt"] = {
            "path": native_path,
            "exists": bool(native_path) and os.path.isfile(native_path),
            "size": os.path.getsize(native_path) if native_path and os.path.isfile(native_path) else 0,
        }
        report["artifacts"]["step"] = {
            "path": step_path,
            "exists": os.path.isfile(step_path),
            "size": os.path.getsize(step_path),
        }
        report["result"] = "success"
        print("NXCAD_RESULT: success")
    except Exception as exc:
        report["result"] = "failure"
        report["error"] = str(exc)
        print("NXCAD_RESULT: failure")
        raise
    finally:
        write_runtime_report(report, report_path)


if __name__ == "__main__":
    main()
