# NX Open Python - raw high-fidelity journal generated by nx-cad skill
# ----------------------------------------------------------------------------
# RUNTIME MODES:
#   - static_only: generate without MCP lookup; the user may run manually.
#   - mcp_review: use MCP lookup to review APIs; do not execute through MCP.
#   - manual_nx: ready for the user to run manually in the NX UI.
#
# CONTROLLED RUNTIME BOUNDARY:
#   The user prepares NX/Designcenter. The agent must not launch or close NX,
#   overwrite prior artifacts, or execute this journal. Runtime evidence comes
#   only from a user-run NX UI session.
# ----------------------------------------------------------------------------

import os
import json

import NXOpen
import NXOpen.Features


RAW_NXOPEN_HIGH_FIDELITY = True

EXECUTION_POLICY = {
    "mode": "mcp_review",
    "manual_user_run_required": True,
    "agent_execution": False,
    "requires_prepared_nx_environment": True,
    "allow_launch_or_close_nx": False,
    "allow_existing_work_part": False,
    "allow_overwrite": False,
    "managed_mode": False,
    "max_repair_attempts": 3,
}

# Replace this with MCP_API_REVIEW when Designcenter/NXOpen MCP tools were used.
STATIC_ONLY_NXOPEN_REVIEW = {
    "reason": "Designcenter/NXOpen MCP tools were not available in this agent session.",
    "checks": [],
}

DESIGN_LEDGER = {
    "capability_level": "experimental_raw",
    "target_nx_version": "unknown",
    "expected_body_count": 1,
    "critical_features": [],
    "optional_features": [],
    "outputs": ["native_prt", "step"],
}


def allocate_run_context():
    journal_base = os.path.splitext(os.path.abspath(__file__))[0]
    sequence = 1
    while True:
        run_id = "run_%03d" % sequence
        run_base = journal_base + "_" + run_id
        candidates = [run_base + suffix for suffix in (".prt", ".step", ".nxreport.json", ".log")]
        if not any(os.path.exists(path) for path in candidates):
            return run_id, run_base
        sequence += 1


def write_runtime_report(report, path):
    with open(path, "w", encoding="utf-8") as stream:
        json.dump(report, stream, indent=2, sort_keys=True)
    print("NXCAD_RUNTIME_REPORT:", path)


def safe_dispose(obj):
    if obj is not None and hasattr(obj, "Dispose"):
        obj.Dispose()


def create_work_part_if_needed(session, part_path):
    work_part = session.Parts.Work
    if work_part is not None and EXECUTION_POLICY["allow_existing_work_part"]:
        print("Using existing NX work part:", work_part)
        return work_part
    if os.path.exists(part_path) or os.path.exists(part_path + ".prt"):
        raise RuntimeError("Refusing to overwrite existing NX part: " + part_path)

    result = session.Parts.NewDisplay(part_path, NXOpen.Part.Units.Millimeters)
    load_status = None
    if isinstance(result, tuple):
        new_part = result[0]
        if len(result) > 1:
            load_status = result[1]
    else:
        new_part = result

    safe_dispose(load_status)
    work_part = session.Parts.Work or new_part
    if work_part is None:
        raise RuntimeError("Could not create an NX work part. Open a part and run the journal again.")

    print("Created NX work part:", part_path)
    return work_part


def export_step(session, work_part, output_path):
    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"

    save_status = work_part.Save(
        NXOpen.BasePart.SaveComponents.TrueValue,
        NXOpen.BasePart.CloseAfterSave.FalseValue,
    )
    safe_dispose(save_status)

    dex_manager = session.DexManager
    step_creator = None
    try:
        display_part_export = hasattr(dex_manager, "CreateStepCreator")
        if display_part_export:
            step_creator = dex_manager.CreateStepCreator()
            step_creator.ExportAs = NXOpen.StepCreator.ExportAsOption.Ap242
            step_creator.ExportFrom = NXOpen.StepCreator.ExportFromOption.DisplayPart
            step_creator.ObjectTypes.Solids = True
            step_creator.FileSaveFlag = False
            step_creator.ProcessHoldFlag = True
        elif hasattr(dex_manager, "CreateStep214Creator"):
            step_creator = dex_manager.CreateStep214Creator()
        else:
            raise RuntimeError("NX DexManager exposes neither CreateStepCreator nor CreateStep214Creator")
        # The raw template uses the live DisplayPart route. Probe 004 separately
        # retains InputFile to isolate the solid-type filter against run 003;
        # neither route is promoted for NX 2606 until returned STEP geometry is
        # inspected successfully.
        if not display_part_export:
            step_creator.InputFile = getattr(work_part, "FullPath", "")
        step_creator.OutputFile = output_path
        step_creator.Commit()
    finally:
        if step_creator is not None:
            step_creator.Destroy()

    if not os.path.isfile(output_path) or os.path.getsize(output_path) <= 0:
        raise RuntimeError("STEP creator returned without a non-empty output file: " + output_path)
    print("Exported STEP:", output_path)
    return output_path


def main():
    session = NXOpen.Session.GetSession()
    run_id, run_base = allocate_run_context()
    report_path = run_base + ".nxreport.json"
    work_part = create_work_part_if_needed(session, run_base)
    session.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Create NX CAD Part")

    report = {
        "schema_version": 2,
        "nx_version": "unknown",
        "probe": os.path.splitext(os.path.basename(__file__))[0],
        "run_id": run_id,
        "result": "running",
        "execution": {
            "actor": "user",
            "transport": "nx_ui",
            "tool": "nx_ui",
        },
        "journal": {
            "path": os.path.abspath(__file__),
            "working_dir": os.path.dirname(os.path.abspath(__file__)),
        },
        "model": {
            "body_count": None,
            "expected_body_count": DESIGN_LEDGER["expected_body_count"],
            "critical_features": {name: False for name in DESIGN_LEDGER["critical_features"]},
        },
        "artifacts": {},
        "warnings": [],
    }

    try:
        # Parameters
        # Define independent prompt parameters and derived dimensions here.

        # Modeling
        # Use direct NXOpen builders, curves, sections, expressions, PMI, save,
        # and export APIs. Every primary and functional failure must propagate.
        # Only optional cosmetics may warn and continue. Wrap every
        # Create*Builder object in try/finally Destroy().
        # After deterministically verifying each required feature, set its
        # report["model"]["critical_features"][name] value to True.

        for name in DESIGN_LEDGER["critical_features"]:
            report["model"]["critical_features"][name] = True
        body_count = len(list(work_part.Bodies))
        report["model"]["body_count"] = body_count
        expected = DESIGN_LEDGER["expected_body_count"]
        if body_count != expected:
            raise RuntimeError(
                "Expected %d final body/bodies, found %d" % (expected, body_count)
            )

        native_path = getattr(work_part, "FullPath", "")
        step_path = run_base + ".step"
        export_step(session, work_part, step_path)
        report["artifacts"]["prt"] = {
            "path": native_path,
            "exists": bool(native_path) and os.path.isfile(native_path),
            "size": os.path.getsize(native_path) if native_path and os.path.isfile(native_path) else 0,
        }
        report["artifacts"]["step"] = {
            "path": step_path,
            "exists": os.path.isfile(step_path),
            "size": os.path.getsize(step_path),
        }
        report["result"] = "success"
        print("NXCAD_RESULT: success")
        print("Raw NXOpen journal completed for work part:", work_part)
    except Exception as exc:
        report["result"] = "failure"
        report["error"] = str(exc)
        print("NXCAD_RESULT: failure")
        raise
    finally:
        write_runtime_report(report, report_path)


if __name__ == "__main__":
    main()
