# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry and exports the STEP file next to this journal.
# ----------------------------------------------------------------------------

import json
import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from cadnx import NXBuilder
from _nx_aerospace_probe_support import write_schema_v2_report


USER_MANUAL_NX_EXECUTION_REQUIRED = True
EXECUTION_POLICY = {
    "mode": "mcp_review",
    "manual_user_run_required": True,
    "agent_execution": False,
    "requires_prepared_nx_environment": True,
    "allow_launch_or_close_nx": False,
    "allow_existing_work_part": False,
    "allow_overwrite": False,
    "managed_mode": False,
    "max_repair_attempts": 3,
}
STATIC_ONLY_NXOPEN_REVIEW = {
    "recipes": ["nx2606.export.step-creator"],
    "note": "Wrapper probe requires NX-machine API review before manual qualification.",
}
DESIGN_LEDGER = {
    "task": "aerospace HPC rear support frame regression fixture",
    "capability_level": "stable_wrapper",
    "target_nx_version": "NX 2606",
    "expected_body_count": 1,
    "critical_features": [
        "annular_casing",
        "central_bearing_hub",
        "primary_and_secondary_struts",
        "flange_hole_patterns",
    ],
    "optional_features": ["cosmetic_chamfers"],
    "outputs": ["native_prt", "step"],
}


def runtime_report_path():
    return os.path.splitext(os.path.abspath(__file__))[0] + ".nxreport.json"


def write_runtime_report(report):
    write_schema_v2_report(__file__, runtime_report_path(), report, DESIGN_LEDGER)


def build(output_path: str = None):
    run_base = os.path.splitext(os.path.abspath(__file__))[0]
    b = NXBuilder(part_path=run_base, force_new_part=True)

    # Coordinate convention: X is engine centerline, radial directions are in YZ.
    x_axis = (1.0, 0.0, 0.0)
    neg_x_axis = (-1.0, 0.0, 0.0)

    # Primary frame dimensions, millimeters.
    casing_od = 520.0
    casing_id = 460.0
    casing_length = 86.0
    casing_x_min = -43.0
    casing_x_max = 43.0

    forward_flange_x = -43.0
    forward_flange_od = 570.0
    forward_flange_id = 455.0
    forward_flange_thickness = 14.0
    forward_flange_hole_count = 36
    forward_flange_hole_diameter = 8.5
    forward_flange_bcd = 535.0

    aft_flange_x = 43.0
    aft_flange_od = 560.0
    aft_flange_id = 458.0
    aft_flange_thickness = 14.0
    aft_flange_hole_count = 36
    aft_flange_hole_diameter = 8.5
    aft_flange_bcd = 525.0
    aft_flange_start_angle_degrees = 5.0

    hub_od = 150.0
    hub_bore_diameter = 82.0
    hub_length = 112.0
    hub_x_min = -56.0
    hub_x_max = 56.0
    forward_seat_diameter = 92.0
    forward_seat_depth = 16.0
    aft_seat_diameter = 96.0
    aft_seat_depth = 18.0

    inner_flange_x = 48.0
    inner_flange_od = 190.0
    inner_flange_id = 82.0
    inner_flange_thickness = 12.0
    inner_flange_hole_count = 16
    inner_flange_hole_diameter = 6.5
    inner_flange_bcd = 168.0

    primary_strut_count = 8
    primary_strut_tangential_chord = 58.0
    primary_strut_axial_thickness = 22.0
    secondary_strut_count = 8
    secondary_strut_tangential_width = 34.0
    secondary_strut_axial_thickness = 16.0

    oil_angle_degrees = 22.5
    oil_passage_diameter = 10.0
    oil_boss_diameter = 24.0
    oil_boss_height = 12.0
    instrumentation_angle_degrees = 202.5
    instrumentation_passage_diameter = 6.0
    instrumentation_boss_diameter = 18.0
    instrumentation_boss_height = 8.0

    # Place the accessory interface midway between the 0-degree primary strut
    # and the 22.5-degree secondary strut.  The previous 90-degree four-hole
    # pad overlapped a primary strut and used full-diameter radial cutters.
    accessory_angle_degrees = 11.25
    accessory_pad_x = 0.0
    accessory_pad_tangential = 42.0
    accessory_pad_axial = 52.0
    accessory_pad_height = 8.0
    accessory_hole_diameter = 6.0
    accessory_axial_pitch_tangential = 20.0

    borescope_angle_degrees = 270.0
    borescope_x = 0.0
    borescope_boss_diameter = 34.0
    borescope_boss_height = 10.0
    borescope_hole_diameter = 12.0

    stiffener_count = 12
    stiffener_start_angle_degrees = 15.0
    stiffener_tangential_width = 24.0
    stiffener_axial_width = 16.0
    stiffener_radial_height = 28.0

    groove_width = 8.0
    groove_depth = 3.0
    groove_x_locations = (-22.0, 22.0)

    feature_overlap = 0.75
    cutter_overlap = 1.0
    through_overcut = 6.0
    chamfer_offset = 0.8

    casing_or = casing_od / 2.0
    casing_ir = casing_id / 2.0
    casing_wall = casing_or - casing_ir
    hub_or = hub_od / 2.0
    forward_flange_or = forward_flange_od / 2.0
    aft_flange_or = aft_flange_od / 2.0
    inner_flange_or = inner_flange_od / 2.0
    strut_radial_length = casing_ir - hub_or + 2.0 * feature_overlap
    strut_radial_center = (casing_ir + hub_or) / 2.0

    b.require_positive(
        casing_length=casing_length,
        casing_wall=(casing_od - casing_id) / 2.0,
        hub_wall=(hub_od - hub_bore_diameter) / 2.0,
        primary_strut_radial_length=strut_radial_length,
    )
    b.require_min_wall(forward_flange_od - forward_flange_id, forward_flange_hole_diameter, 8.0, "forward flange hole lane")
    b.require_min_wall(aft_flange_od - aft_flange_id, aft_flange_hole_diameter, 8.0, "aft flange hole lane")
    b.require_min_wall(inner_flange_od - inner_flange_id, inner_flange_hole_diameter, 8.0, "inner flange hole lane")
    b.require_edge_distance(
        accessory_pad_axial / 2.0,
        accessory_hole_diameter,
        1.0,
        "accessory pad axial hole",
    )
    b.require_edge_distance(
        accessory_pad_tangential / 2.0 - accessory_axial_pitch_tangential / 2.0,
        accessory_hole_diameter,
        1.0,
        "accessory pad tangential hole",
    )
    b.require_feature_budget(
        boolean_operations=140,
        micro_holes=99,
        patterned_features=primary_strut_count + secondary_strut_count + 24 + 3,
        max_boolean_operations=190,
        max_micro_holes=130,
        max_patterned_features=140,
    )

    def radial(angle_degrees):
        a = math.radians(angle_degrees)
        return (0.0, math.cos(a), math.sin(a))

    def tangent(angle_degrees):
        a = math.radians(angle_degrees)
        return (0.0, -math.sin(a), math.cos(a))

    def point_at(x, radius, angle_degrees):
        r = radial(angle_degrees)
        return (x, radius * r[1], radius * r[2])

    def require_single_body(stage):
        body_count = len(list(b.part.Bodies))
        if body_count != 1:
            raise RuntimeError(
                "Rear-frame body-count checkpoint %s found %d bodies"
                % (stage, body_count)
            )

    def unite_annulus(target, outer_diameter, inner_diameter, length, x_start):
        outer = b.cylinder(outer_diameter, length, origin=(x_start, 0.0, 0.0), axis=x_axis)
        bore = b.cylinder(inner_diameter, length + 2.0 * through_overcut, origin=(x_start - through_overcut, 0.0, 0.0), axis=x_axis)
        b.boolean_subtract(outer, bore)
        b.boolean_unite(target, outer)

    frame = b.cylinder(casing_od, casing_length, origin=(casing_x_min, 0.0, 0.0), axis=x_axis)
    casing_bore = b.cylinder(casing_id, casing_length + 2.0 * through_overcut, origin=(casing_x_min - through_overcut, 0.0, 0.0), axis=x_axis)
    b.boolean_subtract(frame, casing_bore)

    unite_annulus(frame, forward_flange_od, forward_flange_id, forward_flange_thickness, forward_flange_x - forward_flange_thickness)
    unite_annulus(frame, aft_flange_od, aft_flange_id, aft_flange_thickness, aft_flange_x)
    unite_annulus(frame, hub_od, hub_bore_diameter, hub_length, hub_x_min)
    unite_annulus(frame, inner_flange_od, inner_flange_id, inner_flange_thickness, inner_flange_x - inner_flange_thickness / 2.0)

    # Bearing seats are represented as coaxial counterbore cuts from each end.
    forward_seat = b.cylinder(forward_seat_diameter, forward_seat_depth + cutter_overlap, origin=(hub_x_min - cutter_overlap, 0.0, 0.0), axis=x_axis)
    b.boolean_subtract(frame, forward_seat)
    aft_seat = b.cylinder(aft_seat_diameter, aft_seat_depth + cutter_overlap, origin=(hub_x_max + cutter_overlap, 0.0, 0.0), axis=neg_x_axis)
    b.boolean_subtract(frame, aft_seat)
    require_single_body("rings_and_bearing_seats")

    for i in range(primary_strut_count):
        angle = i * 360.0 / primary_strut_count
        r = radial(angle)
        t = tangent(angle)
        center = point_at(0.0, strut_radial_center, angle)
        strut = b.oriented_box(
            strut_radial_length,
            primary_strut_tangential_chord,
            primary_strut_axial_thickness,
            center=center,
            u_axis=r,
            v_axis=t,
            w_axis=x_axis,
        )
        nose = b.cylinder(
            primary_strut_tangential_chord,
            primary_strut_axial_thickness,
            origin=(-primary_strut_axial_thickness / 2.0, center[1], center[2]),
            axis=x_axis,
        )
        b.boolean_unite(strut, nose)
        b.boolean_unite(frame, strut)

    for i in range(secondary_strut_count):
        angle = 22.5 + i * 360.0 / secondary_strut_count
        r = radial(angle)
        t = tangent(angle)
        center = point_at(0.0, strut_radial_center, angle)
        strut = b.oriented_box(
            strut_radial_length,
            secondary_strut_tangential_width,
            secondary_strut_axial_thickness,
            center=center,
            u_axis=r,
            v_axis=t,
            w_axis=x_axis,
        )
        tail = b.cylinder(
            secondary_strut_tangential_width,
            secondary_strut_axial_thickness,
            origin=(-secondary_strut_axial_thickness / 2.0, center[1], center[2]),
            axis=x_axis,
        )
        b.boolean_unite(strut, tail)
        b.boolean_unite(frame, strut)
    require_single_body("primary_and_secondary_struts")

    def flange_holes(count, diameter, bcd, start_angle_degrees, x_start, direction):
        for i in range(count):
            angle = start_angle_degrees + i * 360.0 / count
            p = point_at(x_start, bcd / 2.0, angle)
            tool = b.cylinder(diameter, forward_flange_thickness + aft_flange_thickness + 2.0 * through_overcut, origin=p, axis=direction)
            b.boolean_subtract(frame, tool)

    flange_holes(forward_flange_hole_count, forward_flange_hole_diameter, forward_flange_bcd, 0.0, forward_flange_x - forward_flange_thickness - through_overcut, x_axis)
    flange_holes(aft_flange_hole_count, aft_flange_hole_diameter, aft_flange_bcd, aft_flange_start_angle_degrees, aft_flange_x + aft_flange_thickness + through_overcut, neg_x_axis)

    for i in range(inner_flange_hole_count):
        angle = i * 360.0 / inner_flange_hole_count
        p = point_at(inner_flange_x - inner_flange_thickness / 2.0 - through_overcut, inner_flange_bcd / 2.0, angle)
        tool = b.cylinder(inner_flange_hole_diameter, inner_flange_thickness + 2.0 * through_overcut, origin=p, axis=x_axis)
        b.boolean_subtract(frame, tool)

    for groove_x in groove_x_locations:
        groove_outer = b.cylinder(casing_od + 20.0, groove_width, origin=(groove_x - groove_width / 2.0, 0.0, 0.0), axis=x_axis)
        groove_inner = b.cylinder(casing_od - 2.0 * groove_depth, groove_width + 2.0 * cutter_overlap, origin=(groove_x - groove_width / 2.0 - cutter_overlap, 0.0, 0.0), axis=x_axis)
        b.boolean_subtract(groove_outer, groove_inner)
        b.boolean_subtract(frame, groove_outer)
    require_single_body("flange_holes_and_grooves")

    def local_radial_cutter(angle, x_center, start_radius, external_height, wall_depth, hole_diameter):
        """Cut only the near-side feature and casing wall, never the far wall."""
        if external_height <= 0.0 or wall_depth <= 0.0:
            raise ValueError("local radial cutter depths must be positive")
        r = radial(angle)
        origin_radius = start_radius + external_height + through_overcut
        cutter_depth = external_height + wall_depth + 2.0 * through_overcut
        return b.cylinder(
            hole_diameter,
            cutter_depth,
            origin=(x_center, origin_radius * r[1], origin_radius * r[2]),
            axis=(-r[0], -r[1], -r[2]),
        )

    def radial_boss_with_hole(angle, x_center, boss_diameter, boss_height, hole_diameter):
        r = radial(angle)
        outer_start = casing_or - feature_overlap
        boss = b.cylinder(boss_diameter, boss_height + feature_overlap, origin=(x_center, outer_start * r[1], outer_start * r[2]), axis=r)
        b.boolean_unite(frame, boss)
        tool = local_radial_cutter(
            angle,
            x_center,
            casing_or,
            boss_height,
            casing_wall,
            hole_diameter,
        )
        b.boolean_subtract(frame, tool)

    radial_boss_with_hole(oil_angle_degrees, 0.0, oil_boss_diameter, oil_boss_height, oil_passage_diameter)
    radial_boss_with_hole(instrumentation_angle_degrees, 0.0, instrumentation_boss_diameter, instrumentation_boss_height, instrumentation_passage_diameter)
    radial_boss_with_hole(borescope_angle_degrees, borescope_x, borescope_boss_diameter, borescope_boss_height, borescope_hole_diameter)
    require_single_body("local_radial_boss_passages")

    pad_angle = accessory_angle_degrees
    r = radial(pad_angle)
    t = tangent(pad_angle)
    pad_center_radius = casing_or + accessory_pad_height / 2.0 - feature_overlap
    pad = b.oriented_box(
        accessory_pad_tangential,
        accessory_pad_height + feature_overlap,
        accessory_pad_axial,
        center=(accessory_pad_x, pad_center_radius * r[1], pad_center_radius * r[2]),
        u_axis=t,
        v_axis=r,
        w_axis=x_axis,
    )
    b.boolean_unite(frame, pad)
    # Two axial through-holes stay wholly within the united external pad.
    # They do not cross the casing wall or create radial tool bodies in the
    # central opening.
    accessory_hole_radius = casing_or + accessory_pad_height / 2.0
    for st in (-1.0, 1.0):
        tangential_offset = st * accessory_axial_pitch_tangential / 2.0
        tool = b.cylinder(
            accessory_hole_diameter,
            accessory_pad_axial + 2.0 * through_overcut,
            origin=(
                accessory_pad_x - accessory_pad_axial / 2.0 - through_overcut,
                accessory_hole_radius * r[1] + tangential_offset * t[1],
                accessory_hole_radius * r[2] + tangential_offset * t[2],
            ),
            axis=x_axis,
        )
        b.boolean_subtract(frame, tool)
    require_single_body("accessory_pad_and_axial_holes")

    for i in range(stiffener_count):
        angle = stiffener_start_angle_degrees + i * 360.0 / stiffener_count
        r = radial(angle)
        t = tangent(angle)
        for x_center in (forward_flange_x - forward_flange_thickness / 2.0, aft_flange_x + aft_flange_thickness / 2.0):
            stiffener_radius = casing_or + stiffener_radial_height / 2.0 - feature_overlap
            rib = b.oriented_box(
                stiffener_radial_height + feature_overlap,
                stiffener_tangential_width,
                stiffener_axial_width,
                center=(x_center, stiffener_radius * r[1], stiffener_radius * r[2]),
                u_axis=r,
                v_axis=t,
                w_axis=x_axis,
            )
            b.boolean_unite(frame, rib)
    require_single_body("flange_stiffeners")

    # Conservative edge breaks on exposed axial faces. Dense root fillets are left to NX-side refinement if needed.
    b.chamfer(b.get_edges_in_box(frame, (hub_x_min - 1.0, -forward_flange_or - 2.0, -forward_flange_or - 2.0), (hub_x_min + 1.0, forward_flange_or + 2.0, forward_flange_or + 2.0)), chamfer_offset)
    b.chamfer(b.get_edges_in_box(frame, (hub_x_max - 1.0, -aft_flange_or - 2.0, -aft_flange_or - 2.0), (hub_x_max + 1.0, aft_flange_or + 2.0, aft_flange_or + 2.0)), chamfer_offset)
    require_single_body("final_edge_breaks")

    if output_path is None:
        output_path = os.path.splitext(getattr(b.part, "FullPath", ""))[0] + ".step"
    output_path = b.export_step(output_path)
    return b, output_path


def main():
    output = sys.argv[1] if len(sys.argv) > 1 else None
    report = {
        "schema_version": 1,
        "nx_version": "NX 2606",
        "manual_user_run": True,
        "agent_execution": False,
        "probe": "aerospace_hpc_rear_frame",
        "result": "running",
        "body_count": None,
        "features": {},
        "warnings": [],
    }
    try:
        builder, step_path = build(output)
        body_count = len(list(builder.part.Bodies))
        report["body_count"] = body_count
        if body_count != DESIGN_LEDGER["expected_body_count"]:
            raise RuntimeError("Expected one final rear-frame body, found %d" % body_count)
        native_path = getattr(builder.part, "FullPath", "")
        report["native_part"] = {
            "path": native_path,
            "exists": bool(native_path) and os.path.isfile(native_path),
        }
        report["step"] = {
            "path": step_path,
            "exists": os.path.isfile(step_path),
            "size": os.path.getsize(step_path),
        }
        report["features"] = {
            "annular_casing": "success",
            "central_bearing_hub": "success",
            "primary_and_secondary_struts": "success",
            "flange_hole_patterns": "success",
        }
        report["result"] = "success"
        print("NXCAD_RESULT: success")
    except Exception as exc:
        report["result"] = "failure"
        report["error"] = str(exc)
        print("NXCAD_RESULT: failure")
        raise
    finally:
        write_runtime_report(report)


if __name__ == "__main__":
    main()
