# NX Open Python - generated by nx-cad skill
import json
import math
import os
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from cadnx import NXBuilder
from _nx_aerospace_probe_support import write_schema_v2_report


USER_MANUAL_NX_EXECUTION_REQUIRED = True
EXECUTION_POLICY = {
    "mode": "mcp_review",
    "manual_user_run_required": True,
    "agent_execution": False,
    "requires_prepared_nx_environment": True,
    "allow_launch_or_close_nx": False,
    "allow_existing_work_part": False,
    "allow_overwrite": False,
    "managed_mode": False,
    "max_repair_attempts": 3,
}
STATIC_ONLY_NXOPEN_REVIEW = {
    "recipes": ["nx2606.export.step-creator"],
    "note": "Wrapper probe requires NX-machine API review before manual qualification.",
}
DESIGN_LEDGER = {
    "task": "bearing support housing regression fixture",
    "capability_level": "stable_wrapper",
    "target_nx_version": "NX 2606",
    "expected_body_count": 1,
    "critical_features": ["housing", "bearing_seat", "mounting_holes"],
    "optional_features": ["cosmetic_chamfer"],
    "outputs": ["native_prt", "step"],
}


def runtime_report_path():
    return os.path.splitext(os.path.abspath(__file__))[0] + ".nxreport.json"


def write_runtime_report(report):
    write_schema_v2_report(__file__, runtime_report_path(), report, DESIGN_LEDGER)


def build(output_path: str = None):
    b = NXBuilder()

    # Part class: bearing housing block with flange and cover interface.
    housing_diameter = 68.0
    housing_length = 34.0
    foot_length = 88.0
    foot_width = 42.0
    foot_height = 12.0
    bore_diameter = 25.0
    seat_diameter = 47.0
    seat_depth = 7.0
    bolt_circle_diameter = 78.0
    bolt_hole_diameter = 6.6
    feature_overlap = 0.8
    through_overcut = 3.0
    cutter_overlap = 0.8

    b.require_positive(housing_diameter=housing_diameter, housing_length=housing_length, bore_diameter=bore_diameter)
    b.require_min_wall(housing_diameter, seat_diameter, min_wall=6.0, label="bearing seat radial wall")
    b.require_edge_distance((foot_length - bolt_circle_diameter) / 2.0, bolt_hole_diameter, min_ratio=0.75, label="flange bolt edge")
    b.require_feature_budget(boolean_operations=20, micro_holes=4, patterned_features=4)

    foot = b.rounded_box(foot_length, foot_width, foot_height, radius=2.0, origin=(-foot_length / 2.0, -foot_width / 2.0, 0.0))
    housing = b.cylinder(housing_diameter, housing_length + feature_overlap, origin=(0.0, -housing_length / 2.0, foot_height - feature_overlap), axis=(0, 1, 0))
    b.boolean_unite(foot, housing)

    b.bearing_seat(foot, bore_diameter, seat_diameter, housing_length + 2.0 * through_overcut, seat_depth, position=(0.0, -housing_length / 2.0 - cutter_overlap, foot_height), direction=(0, 1, 0), cutter_overlap=cutter_overlap)

    for index in range(4):
        angle = math.radians(45.0 + index * 90.0)
        x = bolt_circle_diameter / 2.0 * math.cos(angle)
        y = bolt_circle_diameter / 2.0 * math.sin(angle) * 0.45
        hole = b.hole(bolt_hole_diameter, foot_height + 2.0 * through_overcut, position=(x, y, -through_overcut), direction=(0, 0, 1))
        b.boolean_subtract(foot, hole)

    b.chamfer(b.get_bottom_edges(foot), 0.8)

    if output_path is None:
        output_path = os.path.splitext(getattr(b.part, "FullPath", ""))[0] + ".step"
    b.export_step(output_path)
    return b, output_path


def main():
    output = sys.argv[1] if len(sys.argv) > 1 else None
    report = {
        "schema_version": 1,
        "nx_version": "NX 2606",
        "manual_user_run": True,
        "agent_execution": False,
        "probe": "nx_benchmark_bearing_housing",
        "result": "running",
        "body_count": None,
        "features": {},
        "warnings": [],
    }
    try:
        builder, step_path = build(output)
        body_count = len(list(builder.part.Bodies))
        report["body_count"] = body_count
        if body_count != DESIGN_LEDGER["expected_body_count"]:
            raise RuntimeError("Expected one final housing body, found %d" % body_count)
        native_path = getattr(builder.part, "FullPath", "")
        report["native_part"] = {
            "path": native_path,
            "exists": bool(native_path) and os.path.isfile(native_path),
        }
        report["step"] = {
            "path": step_path,
            "exists": os.path.isfile(step_path),
            "size": os.path.getsize(step_path),
        }
        report["features"] = {
            "housing": "success",
            "bearing_seat": "success",
            "mounting_holes": "success",
        }
        report["result"] = "success"
        print("NXCAD_RESULT: success")
    except Exception as exc:
        report["result"] = "failure"
        report["error"] = str(exc)
        print("NXCAD_RESULT: failure")
        raise
    finally:
        write_runtime_report(report)


if __name__ == "__main__":
    main()
